name: centinela
description: Proyecto Centinela — alertas comunitarias hiperlocales (MVP).
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  supabase_flutter: ^2.9.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  google_fonts: ^6.2.1
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  shared_preferences: ^2.5.3
  path: ^1.9.1
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  app_links: ^6.4.0
  http: ^1.4.0
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/brand/app_icon.png
  adaptive_icon_background: "#2563EB"
  adaptive_icon_foreground: assets/brand/app_icon_foreground.png

flutter_native_splash:
  color: "#F9FAFB"
  image: assets/brand/splash_logo.png
  android_12:
    color: "#F9FAFB"
    image: assets/brand/splash_logo.png

flutter:
  uses-material-design: true
  assets:
    - env/app.env
    - assets/brand/app_icon.png
    - assets/brand/app_icon_foreground.png
    - assets/brand/splash_logo.png
